---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mechrevo.
--- DateTime: 2022-05-24 23:49
---


local key = KEYS[1]

--/当前线程标识
local threadId = ARGV[1]
local id = redis.call('get', key)

if id == threadId then
    return redis.call('del', key)
end

return 0

