spring:
  profiles:
    active: dev
    include: DB,log,mp,info

infos:
  ip-address:192.168.208.149
  port:28888
  timeout:60
  datasize:10

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
