spring:
  redis:
    host: 192.168.208.129
    port: 6379
    password: 19970311
    lettuce:
      pool:
        max-active: 200
        min-idle: 0
        max-idle: 10
        max-wait: 1000
    database: 3