server:
  port: 18088
  servlet:
    context-path: /boot_first

spring:
  banner:
    image:
      location: logo/wolf.png

datasource:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.208.147/springboot_db
  username: root
  password: 19970311