server:
  port: 9089
spring:
  datasource:
    url: jdbc:mysql://192.168.208.149:3306/hotel?useSSL=false
    username: root
    password: 19970311
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.208.129
    port: 5672
    username: admin
    password: 123456
    virtual-host: my_vhost

logging:
  level:
    cn.evan: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.evan.hotel.pojo

