server:
  port: 18080
  servlet:
    context-path: /boot_mongodb


spring:
  data:
    mongodb:
      uri: mongodb://192.168.208.149:27017,192.168.208.149:27018,192.168.208.149:27019/articledb?connect=replicaSet&slaveOk=true&replicaSet=myrs
#      host: 192.168.208.149
#      database: articledb
#      port: 27017