package com.evan.mybatis.beans;

import lombok.ToString;

@ToString
public class Employee {
    public Employee() {
    }

    public Employee(Integer id, String lastName, String gender, String email, Integer deptId) {
        this.id = id;
        this.lastName = lastName;
        this.gender = gender;
        this.email = email;
        this.deptId = deptId;
    }


    private Integer id;
    private String lastName;
    private String gender;
    private String email;
    private Integer deptId;
    //员工状态
    private EmpStatus empStatus;

    public Integer getId() {
        return id;
    }

    public EmpStatus getEmpStatus() {
        return empStatus;
    }

    public void setEmpStatus(EmpStatus empStatus) {
        this.empStatus = empStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.id
     *
     * @param id the value for tbl_employee.id
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.last_name
     *
     * @return the value of tbl_employee.last_name
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.last_name
     *
     * @param lastName the value for tbl_employee.last_name
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.gender
     *
     * @return the value of tbl_employee.gender
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.gender
     *
     * @param gender the value for tbl_employee.gender
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.email
     *
     * @return the value of tbl_employee.email
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.email
     *
     * @param email the value for tbl_employee.email
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_employee.dept_id
     *
     * @return the value of tbl_employee.dept_id
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_employee.dept_id
     *
     * @param deptId the value for tbl_employee.dept_id
     * @mbg.generated Sat Feb 12 11:59:21 CST 2022
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}